apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: studycafe
type: Opaque
stringData:
  # This is a database password, still in YAML for simplicity in this exercise, 
  # but ideally should also be moved to env vars.
  MYSQL_ROOT_PASSWORD: "1234"
