apiVersion: v1
kind: Secret
metadata:
  name: jasypt-secret
  namespace: studycafe
type: Opaque
stringData:
  JASYPT_ENCRYPTOR_PASSWORD: "my_jasypt_key"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: studycafe
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
