apiVersion: v1
kind: Service
metadata:
  name: broker-1
  namespace: studycafe
  labels:
    app: kafka-broker
spec:
  type: ClusterIP
  ports:
    - name: external
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: internal
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka-broker
