apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-service
  namespace: studycafe
  labels:
    app: study-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
    spec:
      containers:
        - name: study-service
          image: kuuku123/study-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          command:
            - java
            - -jar
            - -Djasypt.encryptor.password=$(JASYPT_ENCRYPTOR_PASSWORD)
            - -Dspring.profiles.active=prod
            - /app/study-service.jar
          env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jasypt-secret
                  key: JASYPT_ENCRYPTOR_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
